### ISSUE TITLE
Mailman to Discourse migration

### ISSUE THREAD

**Issue by ChristianKuehnel** [llvm/llvm-iwg#47]
This epic will track the issues around the Mailman to Discourse migration:

* [x] Agree and merge #45  First draft of roadmap and user guide
* [x] #46 Can we preserve the links to the email archive?
* [x] Share draft of the user guide with the community
* [x] Document the new email archive
* [ ] #48 Find a solution for cross-posting to multiple categories
* [x] Set up email addresses for creating new topics and redirect them to Discourse
* [ ] #94 Define long-term roadmap for mailing list archive
* [ ] update all documentation related to mailing lists

**Comment by tstellar** [comment]
We should collect all the missing features so we can raise them directly to the Discourse team as we have conversations with them about the migration.  They may be able to implement or give us a timeline for new features, like github did when we did that migration.

**Comment by ChristianKuehnel** [comment]
@tstellar please feel free to add tasks to the list on top of this issue.

**Comment by sloppyjuicy** [comment]
@tstellar @ChristianKuehnel

**Comment by ChristianKuehnel** [comment]
@sloppyjuicy , sorry what are you trying to tell me?

**Comment by ChristianKuehnel** [comment]
notes from meeting on 2021-08-03:
- LLVM board wants to move forward with migration
- finalized category list and mailing list mapping
- Up next: getting quote from discourse
- hint: archives could be conserved with static html inside mailman

**Comment by ChristianKuehnel** [comment]
notes from meeting on 2021-08-17:
* completed category mapping
* waiting from quote from Discourse (the company)
* communication to the community in preparation by the board

**Comment by ChristianKuehnel** [comment]
stale effort, removing from out backlog

**Comment by ChristianKuehnel** [comment]
from meeting 2022-01-18:
@ChristianKuehnel reach to @tlattner to figure out if the IWG should help with the migration.
If not: close the issue.

**Comment by ChristianKuehnel** [comment]
@tlattner Is there anything the IWG can do to help with the Discourse migration?
If not I would close this issue.

**Comment by tlattner** [comment]
Now that we have moved, there is lots of cleanup. Mostly documentation related. Anyone can help with that if they see places we need to update things. I'll be working my way through them as well.

**Comment by ChristianKuehnel** [comment]
@tlattner do you have a list of things to improve? You probably have a much deeper insight on what needs to be done.

**Comment by ChristianKuehnel** [comment]
not sure how the IWG can help at the moment --> closing the issue.
